package com.nova.assistant

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** GENERATED by tools/gen_memory_test.py from tools/memory_cases.py (do not edit the tables here: edit memory_cases.py and regenerate). */
class PersonalMemoryTest {
    private val facts = listOf("mera naam shiv hai", "meri car blue hai", "papa ka naam ram hai", "my wifi password is abc", "mummy ka number 9876543210")

    private fun parse(text: String): Logic.Cmd? = PersonalMemory.parse(Logic.norm(text))

    @Test fun parserTableMatchesParseAndClassify() {
        // (text, kind, arg)
        val rows = listOf(
            Triple("nova yaad rakh mera naam Shiv hai", "mem_save", "mera naam shiv hai"),
            Triple("yaad rakho ki meri car blue hai", "mem_save", "meri car blue hai"),
            Triple("Remember that my sister's birthday is in May", "mem_save", "my sister s birthday is in may"),
            Triple("remember my favourite colour is green", "mem_save", "my favourite colour is green"),
            Triple("mujhe yaad rakhna ki kal doctor ke paas jana hai", "mem_save", "kal doctor ke paas jana hai"),
            Triple("mera naam shiv hai yaad rakh", "mem_save", "mera naam shiv hai"),
            Triple("note kar lo meri wifi ka naam home hai", "mem_save", "meri wifi ka naam home hai"),
            Triple("yaad kar lo mere papa ka naam ram hai", "mem_save", "mere papa ka naam ram hai"),
            Triple("please remember i like tea", "mem_save", "i like tea"),
            Triple("hey nova remember that i drink two cups of tea", "mem_save", "i drink two cups of tea"),
            Triple("yaad rakhna ki mujhe subah gym jana hai", "mem_save", "mujhe subah gym jana hai"),
            Triple("mujhe kya yaad hai", "mem_list", null),
            Triple("kya yaad hai", "mem_list", null),
            Triple("tumhe kya yaad hai", "mem_list", null),
            Triple("kya kya yaad hai", "mem_list", null),
            Triple("nova what do you remember", "mem_list", null),
            Triple("what do you remember about me", "mem_list", null),
            Triple("what did i tell you", "mem_list", null),
            Triple("show my memory", "mem_list", null),
            Triple("read me my memories", "mem_list", null),
            Triple("meri yaadein batao", "mem_list", null),
            Triple("bhool ja mera naam", "mem_forget", "mera naam"),
            Triple("bhool jao meri car", "mem_forget", "meri car"),
            Triple("forget my favourite colour", "mem_forget", "my favourite colour"),
            Triple("forget about the car", "mem_forget", "the car"),
            Triple("forget that i like tea", "mem_forget", "i like tea"),
            Triple("mera naam bhool ja", "mem_forget", "mera naam"),
            Triple("mat yaad rakh meri car", "mem_forget", "meri car"),
            Triple("sab bhool ja", "mem_forget_all", null),
            Triple("sab kuch bhool jao", "mem_forget_all", null),
            Triple("saari yaad bhool ja", "mem_forget_all", null),
            Triple("forget everything", "mem_forget_all", null),
            Triple("forget all about me", "mem_forget_all", null),
            Triple("delete all my memories", "mem_forget_all", null),
            Triple("delete my memory", "mem_forget_all", null),
            Triple("yaad dilao 5 minute baad chai", null, null),
            Triple("das minute baad chai yaad dilao", null, null),
            Triple("remind me in 5 minutes", null, null),
            Triple("what time is it", null, null),
            Triple("battery kitni hai", null, null),
            Triple("torch on", null, null),
            Triple("remember", null, null),
            Triple("yaad rakh", null, null),
            Triple("bhool ja", null, null),
            Triple("forget", null, null),
            Triple("wo bhool ja", null, null),
            Triple("i remember my childhood", null, null),
            Triple("mujhe yaad nahi hai", null, null),
            Triple("main bhool jaunga", null, null),
            Triple("tum bhool gaye", null, null)
        )
        for ((text, kind, arg) in rows) {
            val p = parse(text)
            val c = Logic.classify(text)
            if (kind == null) {
                assertNull("parse should ignore: $text", p)
                assertFalse("classify must not give a memory kind: $text", c != null && PersonalMemory.isMemoryKind(c.kind))
            } else {
                assertNotNull("parse: $text", p)
                assertEquals("kind of: $text", kind, p?.kind)
                if (arg != null) assertEquals("arg of: $text", arg, p?.arg)
                assertNotNull("classify: $text", c)
                assertEquals("classify kind of: $text", kind, c?.kind)
                if (arg != null) assertEquals("classify arg of: $text", arg, c?.arg)
            }
        }
    }

    @Test fun refusalTable() {
        val rows = listOf(
            Pair("my wifi password is abc", "secret"),
            Pair("mera otp 4821", "secret"),
            Pair("atm pin 1234", "secret"),
            Pair("my card number is 4111 1111 1111 1111", "card"),
            Pair("cvv 123", "card"),
            Pair("mera aadhaar 1234 5678 9012", "id"),
            Pair("pan card number abcde1234f", "id"),
            Pair("my passport is in the drawer", "id"),
            Pair("bank account number 1234567890", "bank"),
            Pair("mummy ka number 9876543210", "number"),
            Pair("mera number nine eight seven six five four three two one zero", "number"),
            Pair("meri pin code 110001", "secret"),
            Pair("mera naam shiv hai", null),
            Pair("meri umar 25 saal hai", null),
            Pair("my birthday is 12 may 1995", null),
            Pair("meri car ka number 4521", null),
            Pair("i like pineapple pizza", null),
            Pair("papa ka birthday paanch june hai", null),
            Pair("ek do teen char gino", null)
        )
        for ((fact, why) in rows) {
            assertEquals("refuse: $fact", why, PersonalMemory.refuseReason(Logic.norm(fact)))
            val r = PersonalMemory.add(emptyList(), fact)
            if (why == null) assertEquals("saved: $fact", "saved", r.status)
            else {
                assertEquals("refused: $fact", "refused", r.status)
                assertTrue(r.list.isEmpty())
            }
        }
    }

    @Test fun forgetTable() {
        val base = facts.subList(0, 3)
        val rows = listOf(
            Triple("car", 1, false),
            Triple("shiv", 1, false),
            Triple("papa ka naam", 1, false),
            Triple("mera naam", 0, true),
            Triple("kuch nahi", 0, false),
            Triple("", 0, false)
        )
        for ((q, removed, amb) in rows) {
            val r = PersonalMemory.forget(base, q)
            assertEquals("removed for: $q", removed, r.removed)
            assertEquals("ambiguous for: $q", amb, r.ambiguous)
            assertEquals("size after: $q", base.size - removed, r.list.size)
        }
    }

    @Test fun relevantTable() {
        val rows = listOf(
            Pair("meri car ka colour kya hai", listOf("meri car blue hai")),
            Pair("mera naam kya hai", listOf("mera naam shiv hai", "papa ka naam ram hai")),
            Pair("wifi password batao", listOf()),
            Pair("mummy ka number kya hai", listOf()),
            Pair("what is the weather", listOf()),
            Pair("hi", listOf())
        )
        for ((q, want) in rows) assertEquals("relevant for: $q", want, PersonalMemory.relevant(facts, q))
    }

    @Test fun relevantNeverMoreThanThree() {
        val many = (1..10).map { "tea fact number $it about chai" }
        assertEquals(3, PersonalMemory.relevant(many, "tell me about chai").size)
    }

    @Test fun addDedupesIgnoringCaseAndSpaces() {
        val a = PersonalMemory.add(emptyList(), "mera naam shiv hai")
        assertEquals("saved", a.status)
        val b = PersonalMemory.add(a.list, "MERA   naam shiv HAI")
        assertEquals("dup", b.status)
        assertEquals(1, b.list.size)
    }

    @Test fun addLengthLimits() {
        assertEquals("short", PersonalMemory.add(emptyList(), "ab").status)
        assertEquals("long", PersonalMemory.add(emptyList(), "x".repeat(PersonalMemory.MAX_FACT_CHARS + 1)).status)
        assertEquals("saved", PersonalMemory.add(emptyList(), "y".repeat(PersonalMemory.MAX_FACT_CHARS)).status)
    }

    @Test fun listIsLimitedAndNewestFirst() {
        var l: List<String> = emptyList()
        for (i in 0 until PersonalMemory.MAX_FACTS + 5) l = PersonalMemory.add(l, "fact about tea item$i").list
        assertEquals(PersonalMemory.MAX_FACTS, l.size)
        assertTrue(l[0].endsWith("item" + (PersonalMemory.MAX_FACTS + 4)))
        assertFalse(l.any { it.endsWith("item0") })
    }

    @Test fun controlCharactersAndTemplateMarkersAreCleaned() {
        assertEquals("a b c d", PersonalMemory.cleanFact("a\nb\tc<|d|>"))
    }

    @Test fun encodeDecodeRoundTrip() {
        val l = listOf("mera naam shiv hai", "meri car blue hai")
        assertEquals(l, PersonalMemory.decode(PersonalMemory.encode(l)))
        assertEquals(emptyList<String>(), PersonalMemory.decode(null))
        assertEquals(emptyList<String>(), PersonalMemory.decode(""))
    }

    @Test fun factsBlockIsEmptyWithoutFactsAndCapped() {
        assertEquals("", PersonalMemory.factsBlock(emptyList(), true))
        val b = PersonalMemory.factsBlock(listOf("one fact", "two fact", "three fact", "four fact"), true)
        assertTrue(b.contains("three fact"))
        assertFalse(b.contains("four fact"))
    }

    @Test fun repliesNeverEchoARefusedSecret() {
        val r = PersonalMemory.add(emptyList(), "my otp is 5555")
        for (en in listOf(true, false)) {
            assertFalse(PersonalMemory.saveReply(r, en).contains("5555"))
            assertFalse(PersonalMemory.saveReply(r, en).contains("otp is"))
        }
    }

    @Test fun listReplyReadsBackAndHandlesEmpty() {
        assertTrue(PersonalMemory.listReply(emptyList(), true).contains("not remembering"))
        val l = (1..12).map { "fact $it" }
        val s = PersonalMemory.listReply(l, true)
        assertTrue(s.contains("1. fact 1"))
        assertTrue(s.contains("And 4 more"))
        assertFalse(s.contains("fact 12"))
    }

    @Test fun reminderIsStillATimerNotAMemory() {
        val c = Logic.classify("yaad dilao 5 minute baad chai")
        assertFalse(c != null && PersonalMemory.isMemoryKind(c.kind))
    }
}
