# Daily-life entries. General advice only, no medicine doses.
E = [
("daily-boil-water", ["pani ko ubalkar kaise saaf karein", "how to purify water by boiling", "pani kitni der ubalna chahiye", "kitni der ubalne se pani peene layak hota hai", "boiling se pani safe kaise banta hai", "how long to boil water to make it safe"],
 "Pani ko tez ubaal (rolling boil) aane ke baad lagbhag 1 minute ubalo; bahut unchai par 3 minute. Phir use dhak kar thanda hone do aur saaf bartan mein rakho.",
 "Bring the water to a rolling boil and keep it boiling for about 1 minute, or 3 minutes at high altitude. Let it cool covered and store it in a clean container.", ["daily"]),
("daily-cook-rice", ["chawal kaise banate hain", "how to cook rice", "chawal pakane ka tareeka", "rice banane ki vidhi", "chawal aur pani ka anupat kya hota hai", "plain rice kaise pakayein"],
 "Chawal 2-3 baar dhoyo. Aam chawal ke liye lagbhag 1 hissa chawal aur 2 hissa pani lo (basmati mein thoda kam), ubaal aane par dhak kar dheemi aanch par 15 minute pakao. Phir 5 minute dhak kar rehne do.",
 "Rinse the rice 2 to 3 times. Use roughly 1 part rice to 2 parts water (a little less for basmati), cover after it boils and cook on low heat for about 15 minutes. Let it rest covered for 5 minutes.", ["daily", "cooking"]),
("daily-cook-dal", ["dal kaise banate hain", "how to cook dal", "dal pakane ka tareeka", "dal banane ki vidhi", "tadka wali dal kaise banaye", "simple dal recipe"],
 "Dal ko dhokar haldi aur pani ke saath narm hone tak pakao (cooker mein lagbhag 3-4 seeti). Phir ghee ya tel mein jeera, lahsun aur lal mirch ka tadka lagao aur namak daalo.",
 "Wash the dal and cook it with turmeric and water until soft (about 3 to 4 whistles in a pressure cooker). Then add a tempering of cumin, garlic and red chilli in ghee or oil, and add salt.", ["daily", "cooking"]),
("daily-make-tea", ["chai kaise banate hain", "how to make tea", "chai banane ka sahi tareeka", "masala chai kaise banti hai", "perfect chai recipe", "chai banane ki vidhi"],
 "Pani mein adrak aur chai patti ubalo, phir doodh aur cheeni daalo aur 2-3 minute ubalne do. Chhan kar garam garam piyo.",
 "Boil water with ginger and tea leaves, then add milk and sugar and simmer for 2 to 3 minutes. Strain and serve hot.", ["daily", "cooking"]),
("daily-save-electricity", ["bijli kaise bachayein", "how to save electricity", "bijli ka bill kam kaise karein", "electricity bill kam karne ke tareeke", "bijli bachane ke upay", "ways to reduce power consumption"],
 "LED bulb lagao, khali kamre ki light aur pankhe band karo, AC 24 se 26 degree par chalao aur star rating wale upkaran lo. Charger aur TV ko switch se band karo.",
 "Use LED bulbs, switch off lights and fans in empty rooms, run the AC at 24 to 26 degrees and buy star-rated appliances. Switch off chargers and TVs at the socket.", ["daily"]),
("daily-save-money", ["paise kaise bachayein", "how to save money", "50 30 20 rule kya hai", "budget kaise banate hain", "bachat karne ke tareeke", "what is the 50 30 20 rule"],
 "50/30/20 niyam: kamai ka 50% zaruri kharch, 30% shauk aur 20% bachat ya karz chukane mein. Kharch likho aur kamai aate hi pehle bachat alag karo.",
 "The 50/30/20 rule: 50 percent of income for needs, 30 percent for wants and 20 percent for savings or debt. Track spending and set savings aside as soon as income arrives.", ["daily", "finance"]),
("daily-study-pomodoro", ["padhai mein man kaise lagayein", "pomodoro technique kya hai", "how to study better", "what is the pomodoro technique", "padhne ka sabse accha tareeka", "concentration badhane ke tips"],
 "Pomodoro: 25 minute poore dhyan se padho, phir 5 minute ka break lo. 4 round ke baad 15 se 30 minute ka bada break lo. Phone door rakho.",
 "Pomodoro: study with full focus for 25 minutes, then take a 5-minute break. After 4 rounds take a longer break of 15 to 30 minutes. Keep your phone away.", ["daily", "study"]),
("daily-20-20-20", ["aankhon ko thakan se kaise bachayein", "20 20 20 rule kya hai", "what is the 20 20 20 rule", "aankhon ka dard kam karne ka tareeka", "digital eye strain kaise kam karein", "eyes ko aaram kaise dein"],
 "20-20-20 niyam: har 20 minute baad 20 feet (lagbhag 6 meter) door kisi cheez ko 20 second dekho. Palkein jhapkate raho. Dard bana rahe to aankh ke doctor ko dikhao.",
 "The 20-20-20 rule: every 20 minutes look at something 20 feet (about 6 metres) away for 20 seconds. Blink often. If strain persists, see an eye doctor.", ["daily", "health"]),
("daily-posture", ["sahi posture kaisa hota hai", "baithne ka sahi tareeka", "how to sit with good posture", "kamar dard se bachne ke liye kaise baithein", "good posture tips", "reed ki haddi sidhi kaise rakhein"],
 "Peeth kursi se lagi rahe, kandhe dheele, pair zameen par aur kohni lagbhag 90 degree par rakho. Har ghante khade hokar thoda chalo.",
 "Keep your back against the chair, shoulders relaxed, feet flat on the floor and elbows at about 90 degrees. Stand up and walk a little every hour.", ["daily", "health"]),
("daily-sleep-better", ["achhi neend kaise aaye", "how to sleep better", "neend na aaye to kya karein", "better sleep ke tips", "raat ko jaldi neend kaise aaye", "insomnia ke gharelu upay"],
 "Roz ek hi samay par sona aur uthna, sone se pehle caffeine aur phone se door rehna, kamra andhera aur thanda rakhna madad karta hai. Mahino tak neend na aaye to doctor se milo.",
 "Sleep and wake at the same time daily, avoid caffeine and phone use before bed, and keep the room dark and cool. If sleeplessness lasts for weeks, see a doctor.", ["daily", "health"]),
("daily-egg-freshness", ["ande ki taazgi kaise check karein", "egg fresh hai ya nahi kaise pata karein", "how to check if an egg is fresh", "egg float test kya hai", "kharab anda kaise pehchane", "float test for eggs"],
 "Anda thande pani ke glass mein daalo. Taza anda neeche baith jata hai, purana khada ya upar tairta hai. Tairne wale ande ko sungho aur shak ho to phenk do.",
 "Put the egg in a glass of cold water. A fresh egg sinks, an old one stands up or floats. Smell a floating egg and throw it away if in doubt.", ["daily", "cooking"]),
("daily-fresh-vegetables", ["sabziyan taza kaise rakhein", "how to keep vegetables fresh", "sabzi fridge mein kaise rakhein", "hari sabzi ko kharab hone se kaise bachayein", "vegetables ko kaise store karein", "sabzi kitne din taza rehti hai"],
 "Sabzi sukhakar fridge ke sabzi wale khane mein rakho, hari patti kagaz mein lapet kar. Dhone ka kaam use karne se pehle karo. Tamatar aur pyaz alag rakho.",
 "Dry the vegetables and keep them in the fridge crisper, with leafy greens wrapped in paper. Wash them just before use. Store tomatoes and onions separately.", ["daily", "cooking"]),
("daily-clean-phone", ["phone ko kaise saaf karein", "how to clean a phone", "mobile saaf karne ka tareeka", "phone ki safai kaise karte hain", "phone disinfect kaise karein", "phone cleaning tips"],
 "Phone band karo aur charger hata do. Naram, rue na chhodne wale kapde ko halka geela karke ya 70% alcohol wipe se poochho. Port ke andar pani ya liquid mat jaane do.",
 "Switch the phone off and unplug it. Wipe it with a soft, lint-free cloth lightly dampened or a 70 percent alcohol wipe. Do not let liquid enter the ports.", ["daily", "phone"]),
("daily-wet-phone", ["phone pani mein gir jaye to kya karein", "wet phone ko kaise bachayein", "what to do if a phone falls in water", "phone geela ho gaya", "phone bheeg jaye to kya karein", "phone ko chawal mein rakhna chahiye kya"],
 "Phone turant band karo, charge mat karo, cover aur SIM nikalo, bahar se poochho aur hawa wali sookhi jagah rakho. Chawal wali baat ek myth hai, usse madad nahi milti. Service center dikhao.",
 "Switch the phone off at once, do not charge it, remove the case and SIM, wipe it and leave it in a dry, airy place. The rice trick is a myth and does not help. Take it to a service centre.", ["daily", "phone"]),
("daily-strong-password", ["strong password kaise banate hain", "how to make a strong password", "achha password kaisa hona chahiye", "password banane ke tips", "safe password ke niyam", "password manager kya hai"],
 "Lamba password (12 ya zyada akshar), shabdon, ank aur chinh ka mel rakho, aur har account ke liye alag rakho. Naam ya janmatithi mat rakho. Password manager madad karta hai aur 2-step verification ON rakho.",
 "Use a long password (12 or more characters) mixing words, digits and symbols, and a different one for every account. Avoid names and birth dates. A password manager helps; turn on 2-step verification.", ["daily", "safety"]),
("daily-online-fraud", ["online fraud se kaise bachein", "otp kisi ko kyun nahi batana chahiye", "how to avoid online fraud", "fraud call aaye to kya karein", "upi scam se kaise bachein", "online thagi ke case mein kya karein"],
 "OTP, PIN, CVV ya password kisi ko mat batao, chahe wo bank ka naam le. Anjaan link par click mat karo. Thagi ho jaye to turant 1930 par call karo ya cybercrime.gov.in par report karo.",
 "Never share your OTP, PIN, CVV or password, even with someone claiming to be the bank. Do not click unknown links. If you are cheated, call 1930 at once or report at cybercrime.gov.in.", ["daily", "safety"]),
("daily-fire-safety", ["ghar mein aag lag jaye to kya karein", "what to do if there is a fire", "aag lagne par kya karna chahiye", "fire safety ke niyam", "building mein aag lage to lift use karein ya nahi", "aag se kaise bachein"],
 "Shant raho, turant bahar niklo aur lift ka istemal mat karo, seedhiyon se jao. Dhuyein mein jhuk kar chalo, bahar nikalkar 101 ya 112 par call karo aur wapas andar mat jao.",
 "Stay calm, get out at once and do not use the lift; take the stairs. Stay low in smoke, call 101 or 112 from outside and do not go back in.", ["daily", "safety"]),
("daily-earthquake", ["bhukamp aaye to kya karein", "what to do in an earthquake", "earthquake mein kaise bachein", "bhukamp ke dauran safety tips", "drop cover hold on kya hai", "bhukamp mein kahan chhupna chahiye"],
 "Drop, Cover, Hold on: neeche jhuko, mazboot mez ke neeche chhupo aur use pakde raho. Khidki, sheeshe aur bhaari saman se door raho. Jhatke ruke to hi bahar niklo.",
 "Drop, Cover and Hold on: get down, shelter under a sturdy table and hold on. Stay away from windows, glass and heavy furniture. Go outside only after the shaking stops.", ["daily", "safety"]),
("daily-gas-leak", ["gas leak ho jaye to kya karein", "gas cylinder leak hone par kya karna chahiye", "what to do in a gas leak", "ghar mein gas ki badbu aaye to", "lpg leak safety", "gas ki smell aaye to kya karein"],
 "Koi bijli ka switch ya aag mat jalao. Regulator band karo, khidki-darwaze kholo aur sabko bahar nikalo. Bahar se gas company ya 112 par call karo.",
 "Do not touch any electric switch or light a flame. Turn off the regulator, open windows and doors and get everyone outside. Call your gas company or 112 from outside.", ["daily", "safety"]),
("daily-traffic-lights", ["traffic light ke rang ka matlab kya hai", "red light ka matlab kya hota hai", "meaning of traffic light colours", "signal ke laal peele hare rang ka matlab", "what do the traffic signals mean", "traffic signal kaise samjhein"],
 "Laal ka matlab ruko, peele ka matlab ruknay ke liye taiyar ho jao, hare ka matlab aage badho jab raasta saaf ho.",
 "Red means stop, yellow (amber) means get ready to stop and green means go when the way is clear.", ["daily", "safety"]),
("daily-resume", ["acha resume kaise banate hain", "how to make a good resume", "resume mein kya likhna chahiye", "cv kaise banate hain", "resume tips for freshers", "resume likhne ka tareeka"],
 "Resume 1 page ka rakho: naam aur sampark, chhota parichay, shiksha, anubhav ya projects, skills. Har kaam ke saath natija likho, jaise kitna sudhar hua. Galtiyan check karo aur saaf font rakho.",
 "Keep the resume to 1 page: name and contact, short summary, education, experience or projects, and skills. Write results for each task, such as what improved. Proofread and use a clean font.", ["daily", "career"]),
("daily-interview-tips", ["interview ki taiyari kaise karein", "how to prepare for an interview", "interview mein kya poochha jata hai", "interview tips", "job interview mein kaise baat karein", "interview mein accha impression kaise banayein"],
 "Company aur post ke baare mein padho, 'apne baare mein batao' ka chhota jawab taiyar rakho aur samay se pehle pahucho. Saaf aur sach bolo, aur ant mein ek sawaal khud poochho.",
 "Research the company and role, prepare a short answer to 'tell me about yourself' and arrive early. Speak clearly and honestly, and ask one question yourself at the end.", ["daily", "career"]),
("daily-english-speaking", ["english bolna kaise seekhein", "how to improve spoken english", "english speaking improve kaise karein", "english mein fluent kaise bane", "english bolne ki practice kaise karein", "english seekhne ke tips"],
 "Roz 15-20 minute bolo, chahe khud se ya sheeshe ke saamne. Angrezi sunna, chhote vakya banana aur roz 5 naye shabd seekhna madad karta hai. Galti se mat daro.",
 "Speak for 15 to 20 minutes daily, even to yourself or in a mirror. Listening to English, making short sentences and learning 5 new words a day help. Do not fear mistakes.", ["daily", "study"]),
("daily-box-breathing", ["box breathing kya hai", "meditation kaise karein", "tension kam karne ke liye saans kaise lein", "how to do box breathing", "stress kam karne ka tareeka", "dhyan lagane ka sahi tareeka"],
 "Box breathing: 4 ginti tak saans lo, 4 tak roko, 4 tak chhodo, 4 tak ruko, aur ise kuch minute dohrao. Meditation ke liye shant jagah baitho aur saans par dhyan rakho. Zyada tension rahe to doctor se baat karo.",
 "Box breathing: breathe in for 4 counts, hold for 4, breathe out for 4, hold for 4, and repeat for a few minutes. For meditation sit somewhere quiet and follow your breath. If stress is heavy, talk to a doctor.", ["daily", "health"]),
("daily-habits", ["achhi aadat kaise banayein", "how to build a good habit", "aadat banane mein kitna samay lagta hai", "naya habit kaise shuru karein", "habit banane ke tips", "bad habit kaise chhodein"],
 "Chhoti shuruaat karo, roz ek hi samay par karo aur use kisi purani aadat se jodo. Tracker mein tick lagao. Ek din chhoot jaye to chhodo mat, agle din phir shuru karo.",
 "Start tiny, do it at the same time every day and attach it to an existing habit. Tick it off on a tracker. If you miss a day, do not quit; start again the next day.", ["daily"]),
("daily-exercise", ["roz kitni kasrat karni chahiye", "how much exercise do i need", "who ke hisaab se kitna vyayam zaroori hai", "ek hafte mein kitni exercise karni chahiye", "recommended exercise per week", "fit rehne ke liye kitna chalna chahiye"],
 "WHO ke hisaab se bade logon ko hafte mein kam se kam 150 minute madhyam gati ki kasrat, jaise tez chalna, karni chahiye. Bimari ho to shuru karne se pehle doctor se poochho.",
 "The WHO advises adults to do at least 150 minutes of moderate activity such as brisk walking each week. If you have a health condition, ask a doctor before starting.", ["daily", "health"]),
("daily-todo-time", ["productive din kaise banayein", "to do list kaise banate hain", "how to plan my day", "kaam ki list kaise banayein", "productive kaise rahein", "time ka sahi istemal kaise karein"],
 "Roz subah 3 sabse zaruri kaam chuno aur pehle wahi karo. Kaam ko chhote hisson mein baanto, aur ek samay mein ek hi kaam karo. Din ke ant mein agle din ki list banao.",
 "Pick the 3 most important tasks each morning and do them first. Break big jobs into small steps and do one thing at a time. At day's end, write tomorrow's list.", ["daily"]),
]
