# India entries: (id, [question variants], hindi/hinglish answer, english answer, [tags]).  Static facts only.
E = [
("india-capital", ["india ki rajdhani kya hai", "bharat ki rajdhani kaun si hai", "capital of india", "india capital city", "what is the capital of india", "bharat ki capital kya hai"],
 "Bharat ki rajdhani New Delhi hai. Sarkar aur Sansad yahin se chalti hain.",
 "The capital of India is New Delhi, where the central government and Parliament work.", ["india"]),
("india-states-count", ["india mein kul kitne rajya hain", "how many states in india", "bharat mein kitne states hain", "number of states in india", "kul kitne rajya aur kendra shasit pradesh hain", "how many states and union territories does india have"],
 "Bharat mein 28 rajya aur 8 kendra shasit pradesh (union territory) hain.",
 "India has 28 states and 8 union territories.", ["india"]),
("india-states-list", ["india ke saare rajyon ke naam", "list of all states in india", "bharat ke rajyon ki list", "names of indian states", "28 rajya kaun kaun se hain", "india ke states ke naam batao"],
 "28 rajya: Andhra Pradesh, Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Goa, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Karnataka, Kerala, Madhya Pradesh, Maharashtra, Manipur, Meghalaya, Mizoram, Nagaland, Odisha, Punjab, Rajasthan, Sikkim, Tamil Nadu, Telangana, Tripura, Uttar Pradesh, Uttarakhand, West Bengal.",
 "The 28 states: Andhra Pradesh, Arunachal Pradesh, Assam, Bihar, Chhattisgarh, Goa, Gujarat, Haryana, Himachal Pradesh, Jharkhand, Karnataka, Kerala, Madhya Pradesh, Maharashtra, Manipur, Meghalaya, Mizoram, Nagaland, Odisha, Punjab, Rajasthan, Sikkim, Tamil Nadu, Telangana, Tripura, Uttar Pradesh, Uttarakhand, West Bengal.", ["india"]),
("india-uts-list", ["india ke kendra shasit pradesh kaun se hain", "union territories of india list", "bharat ke 8 union territory ke naam", "names of union territories in india", "kendra shasit pradesh ke naam batao", "list of union territories"],
 "8 kendra shasit pradesh: Andaman aur Nicobar Islands, Chandigarh, Dadra aur Nagar Haveli aur Daman aur Diu, Delhi, Jammu aur Kashmir, Ladakh, Lakshadweep, Puducherry.",
 "The 8 union territories: Andaman and Nicobar Islands, Chandigarh, Dadra and Nagar Haveli and Daman and Diu, Delhi, Jammu and Kashmir, Ladakh, Lakshadweep and Puducherry.", ["india"]),
("india-national-animal", ["india ka rashtriya janwar kaun sa hai", "national animal of india", "bharat ka rashtriya pashu kya hai", "india national animal kya hai", "what is the national animal of india", "rashtriya janwar kaun hai"],
 "Bharat ka rashtriya janwar Bengal tiger (baagh) hai.",
 "The national animal of India is the Bengal tiger.", ["india"]),
("india-national-bird", ["india ka rashtriya pakshi kaun sa hai", "national bird of india", "bharat ka rashtriya pakshi kya hai", "india national bird kya hai", "what is the national bird of india", "rashtriya pakshi kaun hai"],
 "Bharat ka rashtriya pakshi mor (Indian peacock) hai.",
 "The national bird of India is the Indian peacock.", ["india"]),
("india-national-flower", ["india ka rashtriya phool kaun sa hai", "national flower of india", "bharat ka rashtriya phool kya hai", "india national flower kya hai", "what is the national flower of india", "rashtriya phool kaun sa hai"],
 "Bharat ka rashtriya phool kamal (lotus) hai.",
 "The national flower of India is the lotus.", ["india"]),
("india-national-fruit", ["india ka rashtriya phal kaun sa hai", "national fruit of india", "bharat ka rashtriya phal kya hai", "india national fruit kya hai", "what is the national fruit of india", "rashtriya phal kaun sa hai"],
 "Bharat ka rashtriya phal aam (mango) hai.",
 "The national fruit of India is the mango.", ["india"]),
("india-national-tree", ["india ka rashtriya ped kaun sa hai", "national tree of india", "bharat ka rashtriya vriksh kya hai", "india national tree kya hai", "what is the national tree of india", "rashtriya ped kaun sa hai"],
 "Bharat ka rashtriya ped bargad (banyan) hai.",
 "The national tree of India is the banyan.", ["india"]),
("india-national-anthem", ["india ka rashtra gaan kya hai", "national anthem of india", "jana gana mana kisne likha", "bharat ka rashtriya gaan kaun sa hai", "who wrote the indian national anthem", "rashtra gan kisne likha"],
 "Bharat ka rashtra gaan Jana Gana Mana hai. Ise Rabindranath Tagore ne likha tha.",
 "India's national anthem is Jana Gana Mana, written by Rabindranath Tagore.", ["india"]),
("india-national-song", ["india ka rashtriya geet kya hai", "national song of india", "vande mataram kisne likha", "bharat ka rashtriya geet kaun sa hai", "who wrote vande mataram", "rashtriya geet kisne likha"],
 "Bharat ka rashtriya geet Vande Mataram hai. Ise Bankim Chandra Chatterjee ne likha tha.",
 "India's national song is Vande Mataram, written by Bankim Chandra Chatterjee.", ["india"]),
("india-flag", ["tiranga mein kaun kaun se rang hote hain", "colours of the indian flag", "bharat ke jhande mein kitne rang hain", "indian flag colours", "tirange ka chakra kaisa hai", "how many spokes in the ashoka chakra"],
 "Tirange mein upar kesariya, beech mein safed aur neeche hara rang hota hai. Safed patti ke beech neele rang ka Ashoka chakra hai, jisme 24 tiliyan hoti hain.",
 "The Indian flag has saffron on top, white in the middle and green at the bottom. The navy blue Ashoka Chakra in the white band has 24 spokes.", ["india"]),
("india-independence-day", ["india ko azadi kab mili", "when did india get independence", "swatantrata diwas kab hota hai", "15 august 1947 ko kya hua tha", "bharat azad kab hua", "india independence day kab hai"],
 "Bharat 15 August 1947 ko angrezi raj se azad hua. Isliye har saal 15 August ko Swatantrata Diwas manaya jata hai.",
 "India became independent from British rule on 15 August 1947, so Independence Day is celebrated every year on 15 August.", ["india"]),
("india-republic-day", ["gantantra diwas kab manaya jata hai", "republic day kab hai", "26 january 1950 ko kya hua tha", "26 january kyun manate hain", "why is republic day celebrated on 26 january", "republic day kyun manaya jata hai"],
 "26 January 1950 ko Bharat ka Samvidhan lagu hua aur Bharat gantantra bana. Isliye har saal 26 January ko Gantantra Diwas manate hain.",
 "The Constitution of India came into effect on 26 January 1950 and India became a republic. That is why Republic Day is celebrated on 26 January.", ["india"]),
("india-constitution", ["bharat ka samvidhan kab bana", "indian constitution kisne likha", "constitution of india kab adopt hua", "samvidhan banane wali drafting committee ke adhyaksh kaun the", "who is the father of the indian constitution", "samvidhan kab apnaya gaya"],
 "Samvidhan sabha ne Samvidhan 26 November 1949 ko apnaya aur ye 26 January 1950 se lagu hua. Drafting committee ke adhyaksh Ambedkar the.",
 "The Constituent Assembly adopted the Constitution on 26 November 1949 and it came into force on 26 January 1950. Ambedkar chaired the Drafting Committee.", ["india"]),
("india-first-pm", ["bharat ke pehle pradhanmantri kaun the", "first prime minister of india", "india ke pehle pm kaun the", "who was the first pm of india", "swatantra bharat ke pehle pradhanmantri", "pehle pradhan mantri ka naam"],
 "Swatantra Bharat ke pehle pradhanmantri Jawaharlal Nehru the.",
 "The first Prime Minister of independent India was Jawaharlal Nehru.", ["india"]),
("india-first-president", ["bharat ke pehle rashtrapati kaun the", "first president of india", "india ke pehle president kaun the", "who was the first president of india", "swatantra bharat ke pehle rashtrapati", "pehle rashtrapati ka naam"],
 "Bharat ke pehle rashtrapati Dr Rajendra Prasad the.",
 "The first President of India was Rajendra Prasad.", ["india"]),
("india-longest-river", ["india ki sabse lambi nadi kaun si hai", "longest river in india", "bharat ki sabse badi nadi kaun si hai", "ganga kitni lambi hai", "how long is the ganga river", "bharat mein sabse lambi nadi"],
 "Ganga Bharat ki sabse lambi nadi hai, lagbhag 2,525 km lambi. Brahmaputra aur Sindhu zyada lambi hain par unka bada hissa Bharat ke bahar behta hai.",
 "The Ganga is India's longest river at about 2,525 km. The Brahmaputra and the Indus are longer overall, but much of their course is outside India.", ["india"]),
("india-highest-peak", ["india ki sabse unchi choti kaun si hai", "highest peak in india", "bharat ka sabse ooncha parvat kaun sa hai", "kangchenjunga kitna uncha hai", "how high is kangchenjunga", "india ka sabse uncha pahad"],
 "Kangchenjunga (lagbhag 8,586 meter) Bharat ki sabse unchi choti hai. Ye Sikkim aur Nepal ki seema par hai aur duniya ki teesri sabse unchi choti hai.",
 "Kangchenjunga (about 8,586 metres) is the highest peak in India. It lies on the Sikkim-Nepal border and is the third highest mountain in the world.", ["india"]),
("india-largest-state", ["india ka sabse bada rajya kaun sa hai", "largest state in india by area", "kshetrafal mein sabse bada rajya", "bharat ka sabse bada state kaun sa hai", "which is the biggest state of india", "rajasthan kitna bada rajya hai"],
 "Kshetrafal ke hisaab se Rajasthan Bharat ka sabse bada rajya hai.",
 "By area, Rajasthan is the largest state of India.", ["india"]),
("india-smallest-state", ["india ka sabse chhota rajya kaun sa hai", "smallest state in india", "kshetrafal mein sabse chhota rajya", "bharat ka sabse chota state kaun sa hai", "which is the smallest state of india", "goa kitna bada rajya hai"],
 "Kshetrafal ke hisaab se Goa Bharat ka sabse chhota rajya hai.",
 "By area, Goa is the smallest state of India.", ["india"]),
("india-most-populous-state", ["india ka sabse zyada aabadi wala rajya kaun sa hai", "most populous state in india", "sabse zyada jansankhya wala rajya", "bharat ka sabse badi aabadi wala state", "which state has the highest population in india", "uttar pradesh ki aabadi sabse zyada hai kya"],
 "2011 ki janganana ke hisaab se Uttar Pradesh Bharat ka sabse zyada aabadi wala rajya hai.",
 "As per the 2011 census, Uttar Pradesh is the most populous state of India.", ["india"]),
("india-currency", ["india ki mudra kya hai", "currency of india", "bharat ka paisa kya kehlata hai", "rupee ke notes kaun chhapta hai", "who issues indian rupee notes", "rbi kya hai"],
 "Bharat ki mudra rupaya (₹) hai. Notes Reserve Bank of India (RBI) jaari karta hai, jo desh ka kendriya bank hai.",
 "India's currency is the rupee (₹). Notes are issued by the Reserve Bank of India (RBI), the country's central bank.", ["india"]),
("india-taj-mahal", ["taj mahal kahan hai", "taj mahal kisne banwaya", "who built the taj mahal", "where is the taj mahal", "taj mahal kab bana", "taj mahal ke baare mein batao"],
 "Taj Mahal Agra (Uttar Pradesh) mein Yamuna nadi ke kinare hai. Ise Mughal badshah Shah Jahan ne apni begum Mumtaz Mahal ki yaad mein banwaya tha.",
 "The Taj Mahal is in Agra, Uttar Pradesh, on the banks of the Yamuna. The Mughal emperor Shah Jahan built it in memory of his wife Mumtaz Mahal.", ["india"]),
("india-red-fort", ["lal qila kahan hai", "lal kila kisne banwaya", "who built the red fort", "where is the red fort", "red fort kahan hai", "lal qila ke baare mein batao"],
 "Lal Qila Delhi mein hai. Ise Mughal badshah Shah Jahan ne lal balua pathar se banwaya tha, aur 15 August ko pradhanmantri yahin se tiranga fahrate hain.",
 "The Red Fort is in Delhi. The Mughal emperor Shah Jahan built it from red sandstone, and the Prime Minister hoists the flag there on 15 August.", ["india"]),
("india-gate", ["india gate kahan hai", "india gate kisne banwaya", "india gate kis liye bana hai", "where is india gate", "what is india gate", "india gate ke baare mein batao"],
 "India Gate New Delhi mein ek yaad-gaar (war memorial) hai, jo pehle vishwa yuddh mein shaheed hue Bharatiya sainikon ki yaad mein banaya gaya. Iska design Edwin Lutyens ne banaya tha.",
 "India Gate is a war memorial in New Delhi, built in memory of Indian soldiers who died in the First World War. It was designed by Edwin Lutyens.", ["india"]),
("india-parliament", ["sansad mein kitne sadan hote hain", "lok sabha mein kitni seats hain", "how many seats in lok sabha", "rajya sabha mein kitne sadasya hote hain", "indian parliament houses", "lok sabha aur rajya sabha kya hai"],
 "Bharat ki Sansad ke do sadan hain: Lok Sabha (543 nirvachit seat) aur Rajya Sabha (adhiktam 250 sadasya).",
 "India's Parliament has two houses: the Lok Sabha (543 elected seats) and the Rajya Sabha (a maximum of 250 members).", ["india"]),
("india-voting-age", ["india mein vote dene ki umar kitni hai", "voting age in india", "kitne saal ki umar mein vote de sakte hain", "minimum age to vote in india", "matdan ki nyunatam aayu", "vote dene ki age kya hai"],
 "Bharat mein 18 saal ya usse zyada umar ke nagrik vote de sakte hain.",
 "In India, citizens aged 18 or above can vote.", ["india"]),
("india-gandhi-jayanti", ["gandhi jayanti kab hoti hai", "mahatma gandhi ka janm kab hua", "when is gandhi jayanti", "gandhi ji kab paida hue the", "mahatma gandhi birthday", "2 october ko kya hota hai"],
 "Gandhi Jayanti har saal 2 October ko hoti hai. Mahatma Gandhi ka janm 2 October 1869 ko Porbandar (Gujarat) mein hua tha.",
 "Gandhi Jayanti is on 2 October every year. Mahatma Gandhi was born on 2 October 1869 in Porbandar, Gujarat.", ["india"]),
("india-national-language", ["india ki rashtriya bhasha kya hai", "national language of india", "bharat ki rashtra bhasha kaun si hai", "kya hindi rashtriya bhasha hai", "is hindi the national language of india", "india mein kitni official languages hain"],
 "Bharat ke Samvidhan mein koi rashtriya bhasha tay nahi hai. Kendra sarkar ki official bhashayein Hindi aur Angrezi hain, aur Aathvi Anusuchi mein 22 bhashayein hain.",
 "India's Constitution names no national language. Hindi and English are the official languages of the Union government, and 22 languages are listed in the Eighth Schedule.", ["india"]),
("india-time-zone", ["india ka time zone kya hai", "ist ka matlab kya hai", "india standard time utc se kitna aage hai", "what is ist", "indian time zone kya hai", "india mein kitne time zone hain"],
 "Bharat ka standard samay IST (Indian Standard Time) hai, jo UTC se 5 ghante 30 minute aage hai. Poore desh mein ek hi samay chalta hai.",
 "Indian Standard Time (IST) is UTC plus 5 hours 30 minutes. The whole country follows this one time zone.", ["india"]),
("india-isro", ["isro kya hai", "isro ka full form kya hai", "what is isro", "india ki space agency kaun si hai", "isro ka matlab", "full form of isro"],
 "ISRO ka matlab Indian Space Research Organisation hai. Ye Bharat ki antariksh agency hai jo satellite aur rocket banati aur chhodti hai.",
 "ISRO stands for Indian Space Research Organisation. It is India's space agency and builds and launches satellites and rockets.", ["india"]),
("india-chandrayaan3", ["chandrayaan 3 kab utra", "chandrayaan 3 ki landing kab hui", "when did chandrayaan 3 land on the moon", "chandrayaan 3 kya hai", "chandrayaan 3 kahan utra tha", "chandrayaan 3 landing kab hui thi"],
 "ISRO ka Chandrayaan-3 23 August 2023 ko chand ke dakshini dhruv ke paas safalta se utra. Bharat chand par utarne wala chautha desh bana.",
 "ISRO's Chandrayaan-3 landed successfully near the Moon's south pole on 23 August 2023. India became the fourth country to land on the Moon.", ["india", "space"]),
("india-pin-code", ["pin code mein kitne digit hote hain", "pin code kya hota hai", "how many digits in an indian pin code", "what is a pin code", "postal pin code kitne number ka hota hai", "pincode ka matlab"],
 "Bharat ka PIN code 6 ank ka hota hai. Pehla ank ilake (zone) ko dikhata hai aur aakhri ank us dak ghar ko.",
 "An Indian PIN code has 6 digits. The first digit shows the postal zone and the last digits point to the delivery post office.", ["india"]),
("india-aadhaar", ["aadhaar number kitne digit ka hota hai", "aadhaar kya hai", "what is aadhaar", "aadhar card mein kitne ank hote hain", "how many digits in aadhaar", "aadhaar kaun jaari karta hai"],
 "Aadhaar 12 ank ki pehchan sankhya hai jo UIDAI jaari karta hai. Apna Aadhaar number aur OTP anjaan logon ko mat do.",
 "Aadhaar is a 12-digit identity number issued by UIDAI. Do not share your Aadhaar number or OTP with strangers.", ["india", "safety"]),
("india-upi", ["upi kya hai", "upi se paise kaise bhejte hain", "what is upi", "upi ka full form", "upi pin kya hota hai", "upi payment kaise kaam karta hai"],
 "UPI se aap phone se seedhe bank khate se paise bhej sakte ho. UPI PIN sirf paise bhejne ke waqt daalna hota hai, paise lene ke liye nahi. PIN kisi ko mat batao.",
 "UPI lets you send money straight from your bank account using your phone. The UPI PIN is needed only to send money, never to receive it. Never share your PIN with anyone.", ["india", "safety"]),
("india-neighbours", ["india ke padosi desh kaun se hain", "neighbouring countries of india", "bharat ki seema kin deshon se lagti hai", "which countries share a land border with india", "india ke padosi mulk", "bharat ke padosi deshon ke naam"],
 "Bharat ki zameen ki seema Pakistan, China, Nepal, Bhutan, Bangladesh aur Myanmar se lagti hai.",
 "India shares land borders with Pakistan, China, Nepal, Bhutan, Bangladesh and Myanmar.", ["india"]),
("india-diwali", ["diwali kya hai", "diwali kyun manate hain", "what is diwali", "why is diwali celebrated", "deepawali ke baare mein batao", "diwali ka tyohar kab manate hain"],
 "Diwali (Deepawali) roshni ka tyohar hai jo ghar mein diye jalakar, mithai baantkar aur Lakshmi pujan karke manaya jata hai. Ye aam taur par October ya November mein aata hai, tithi har saal badalti hai.",
 "Diwali (Deepawali) is the festival of lights, celebrated with diyas, sweets and Lakshmi puja. It falls in October or November and the date changes every year.", ["india", "festival"]),
("india-holi", ["holi kya hai", "holi kyun manate hain", "what is holi", "why is holi celebrated", "holi ke baare mein batao", "holi ka tyohar kab aata hai"],
 "Holi rangon ka tyohar hai jo basant ritu mein, aam taur par March mein manaya jata hai. Log ek doosre par rang lagate aur mithai baantte hain.",
 "Holi is the festival of colours, usually celebrated in March at the start of spring. People play with colours and share sweets.", ["india", "festival"]),
]
