# Math entries: formulas and fixed facts only (no calculation: LocalSkills does the sums).
E = [
("math-area-rectangle", ["rectangle ka area kaise nikalte hain", "area of a rectangle formula", "aayat ka kshetrafal", "rectangle ka kshetrafal kya hota hai", "how to find the area of a rectangle", "rectangle area formula"],
 "Aayat ka kshetrafal = lambai x chaudai.",
 "Area of a rectangle = length x width.", ["math"]),
("math-area-square", ["square ka area kaise nikalte hain", "area of a square formula", "varg ka kshetrafal", "square ka kshetrafal kya hota hai", "how to find the area of a square", "square area formula"],
 "Varg (square) ka kshetrafal = bhuja x bhuja.",
 "Area of a square = side x side.", ["math"]),
("math-area-circle", ["circle ka area kaise nikalte hain", "area of a circle formula", "vritt ka kshetrafal", "gole ka kshetrafal kya hota hai", "how to find the area of a circle", "circle area formula"],
 "Vritt (circle) ka kshetrafal = pi x trijya x trijya, yani pi x r x r.",
 "Area of a circle = pi x radius x radius, that is pi x r x r.", ["math"]),
("math-circumference", ["circle ki paridhi kaise nikalte hain", "circumference of a circle formula", "vritt ki paridhi kya hoti hai", "circle ka perimeter", "how to find the circumference of a circle", "paridhi ka formula"],
 "Vritt ki paridhi = 2 x pi x trijya.",
 "Circumference of a circle = 2 x pi x radius.", ["math"]),
("math-area-triangle", ["triangle ka area kaise nikalte hain", "area of a triangle formula", "tribhuj ka kshetrafal", "triangle ka kshetrafal kya hota hai", "how to find the area of a triangle", "triangle area formula"],
 "Tribhuj ka kshetrafal = aadha x aadhar x unchai.",
 "Area of a triangle = half x base x height.", ["math"]),
("math-perimeter-rectangle", ["rectangle ka perimeter kaise nikalte hain", "perimeter of a rectangle formula", "aayat ki paridhi", "rectangle ki paridhi kya hoti hai", "how to find the perimeter of a rectangle", "rectangle perimeter formula"],
 "Aayat ki paridhi = 2 x (lambai + chaudai).",
 "Perimeter of a rectangle = 2 x (length + width).", ["math"]),
("math-pythagoras", ["pythagoras theorem kya hai", "pythagoras ka niyam", "pythagorean theorem formula", "what is the pythagoras theorem", "samkon tribhuj ka pythagoras prameya", "pythagoras formula batao"],
 "Samkon tribhuj mein karn ka varg baaki do bhujaon ke vargon ke jod ke barabar hota hai: a x a + b x b = c x c, jahan c sabse badi bhuja (karn) hai.",
 "In a right-angled triangle the square of the hypotenuse equals the sum of the squares of the other two sides: a x a + b x b = c x c, where c is the longest side.", ["math"]),
("math-percentage", ["percentage kaise nikalte hain", "percentage ka formula kya hai", "how to calculate percentage", "percentage formula", "pratishat kaise nikalte hain", "percent nikalne ka tareeka"],
 "Pratishat = (hissa / kul) x 100. Jaise 20 mein se 5 ka pratishat = 5 / 20 x 100 = 25.",
 "Percentage = (part / whole) x 100. For example 5 out of 20 is 5 / 20 x 100 = 25 percent.", ["math"]),
("math-simple-interest", ["simple interest ka formula kya hai", "sadharan byaj kaise nikalte hain", "simple interest formula", "how to calculate simple interest", "sa byaj ka formula", "si ka formula batao"],
 "Sadharan byaj (SI) = (mool dhan x dar x samay) / 100, jahan dar saalana percent mein aur samay saal mein ho.",
 "Simple interest (SI) = (principal x rate x time) / 100, with the rate in percent per year and time in years.", ["math", "finance"]),
("math-compound-interest", ["compound interest ka formula kya hai", "chakravriddhi byaj kaise nikalte hain", "compound interest formula", "how to calculate compound interest", "ci ka formula batao", "chakravridhi byaj ka formula"],
 "Chakravriddhi byaj mein mishradhan A = P x (1 + r/100) ki ghaat n hoti hai, jahan P mool dhan, r saalana dar aur n saal hain. Byaj = A - P.",
 "In compound interest the amount A = P x (1 + r/100) raised to the power n, where P is the principal, r the yearly rate and n the years. Interest = A - P.", ["math", "finance"]),
("math-average", ["average kaise nikalte hain", "ausat ka formula kya hai", "how to calculate average", "average formula", "mean kaise nikalte hain", "ausat nikalne ka tareeka"],
 "Ausat = sab sankhyaon ka jod / sankhyaon ki ginti. Jaise 4, 6 aur 8 ka ausat = 18 / 3 = 6.",
 "Average = sum of all the numbers / how many numbers there are. For example the average of 4, 6 and 8 is 18 / 3 = 6.", ["math"]),
("math-prime", ["prime number kya hota hai", "ghatak sankhya kise kehte hain", "what is a prime number", "prime number ki definition", "abhajya sankhya kya hoti hai", "first few prime numbers"],
 "Abhajya (prime) sankhya wo hai jo sirf 1 aur khud se bhaag hoti hai, jaise 2, 3, 5, 7, 11. 2 sabse chhoti prime hai aur ekmatra even prime bhi.",
 "A prime number is divisible only by 1 and itself, like 2, 3, 5, 7, 11. 2 is the smallest prime and the only even prime.", ["math"]),
("math-even-odd", ["even odd number kya hote hain", "sam aur visham sankhya kya hoti hai", "what are even and odd numbers", "even number kise kehte hain", "odd number kya hota hai", "even aur odd mein kya fark hai"],
 "Jo sankhya 2 se poori bhaag ho wo sam (even) hai, jaise 2, 4, 6. Baaki visham (odd) hain, jaise 1, 3, 5.",
 "A number that divides exactly by 2 is even, like 2, 4, 6. The rest are odd, like 1, 3, 5.", ["math"]),
("math-speed-distance-time", ["speed distance formula batao", "chaal doori aur samay ka sambandh", "speed kaise nikalte hain", "formula of speed distance and time", "raftaar kaise nikalte hain", "how to calculate speed"],
 "Chaal = doori / samay. Isi se doori = chaal x samay aur samay = doori / chaal.",
 "Speed = distance / time. From it, distance = speed x time and time = distance / speed.", ["math"]),
("math-pi", ["pi ki value kitni hoti hai", "pi kya hota hai", "what is the value of pi", "value of pi kya hai", "pai ka maan kitna hota hai", "what is pi in maths"],
 "Pi vritt ki paridhi aur vyas ka anupat hai. Iska maan lagbhag 3.14159 hai (aksar 3.14 ya 22/7 liya jata hai).",
 "Pi is the ratio of a circle's circumference to its diameter. Its value is about 3.14159 (often taken as 3.14 or 22/7).", ["math"]),
("math-lakh-crore", ["1 lakh mein kitne hazaar hote hain", "crore mein kitne lakh hote hain", "lakh crore million billion ka relation", "ek crore mein kitne lakh", "1 million mein kitne lakh hote hain", "how many lakhs make a crore"],
 "1 lakh = 1,00,000 (100 hazaar). 1 crore = 100 lakh = 1,00,00,000. 1 million = 10 lakh aur 1 billion = 100 crore.",
 "1 lakh = 100,000. 1 crore = 100 lakh = 10,000,000. 1 million = 10 lakh and 1 billion = 100 crore.", ["math"]),
("math-leap-year", ["leap year kaise pehchante hain", "leap year ka rule kya hai", "kaun sa saal leap year hota hai", "how do you know if a year is a leap year", "leap year rule", "adhik varsh kise kehte hain"],
 "Jo saal 4 se bhaag ho wo leap year hai, par sau wale saal (jaise 1900) tab tak nahi jab tak 400 se bhaag na hon. Isliye 2000 leap year tha aur 1900 nahi.",
 "A year divisible by 4 is a leap year, but century years like 1900 are leap years only if divisible by 400. So 2000 was a leap year and 1900 was not.", ["math"]),
("math-lcm-hcf", ["lcm aur hcf kya hote hain", "lcm kaise nikalte hain", "hcf kaise nikalte hain", "what are lcm and hcf", "how to find the lcm", "lasaapavartya aur mahattam samapavartak"],
 "LCM wo sabse chhoti sankhya hai jo dono sankhyaon se poori bhaag ho. HCF wo sabse badi sankhya hai jo dono ko poora bhaag kare. Dono ka sambandh: LCM x HCF = pehli sankhya x doosri sankhya.",
 "The LCM is the smallest number divisible by both numbers. The HCF is the largest number that divides both. For two numbers, LCM x HCF = first number x second number.", ["math"]),
("math-roman-numerals", ["roman numerals kya hote hain", "roman numbers kaise likhte hain", "roman numeral ke symbols", "what are roman numerals", "roman v x l c d m ka matlab", "roman ank kaise likhte hain"],
 "Roman ank: I=1, V=5, X=10, L=50, C=100, D=500, M=1000. Chhota ank bade ke pehle ho to ghatate hain (IV=4), baad mein ho to jodte hain (VI=6).",
 "Roman numerals: I=1, V=5, X=10, L=50, C=100, D=500, M=1000. A smaller symbol before a larger one is subtracted (IV=4), after it is added (VI=6).", ["math"]),
("math-fraction-percent", ["fraction ko percentage mein kaise badlein", "bhinn ko pratishat mein kaise badalte hain", "how to convert a fraction to a percentage", "fraction to percent", "decimal ko percent mein kaise badlein", "fraction se percent nikalna"],
 "Bhinn ko pratishat banane ke liye upar wali sankhya ko neeche wali se bhaag do aur 100 se guna karo. Jaise 3/4 = 0.75 x 100 = 75 percent.",
 "To turn a fraction into a percentage, divide the top number by the bottom number and multiply by 100. For example 3/4 = 0.75 x 100 = 75 percent.", ["math"]),
("math-bodmas", ["bodmas kya hai", "bodmas ka rule", "what is bodmas", "order of operations in maths", "pemdas kya hota hai", "sankhyaon ke sawal mein pehle kya karein"],
 "BODMAS ka kram: Brackets, Orders (ghaat), Division, Multiplication, Addition, Subtraction. Pehle bracket, phir ghaat, phir bhaag aur guna, aakhir mein jod aur ghata (baayen se daayen).",
 "BODMAS is the order of operations: Brackets, Orders (powers), Division, Multiplication, Addition, Subtraction. Do brackets first, then powers, then division and multiplication, and addition and subtraction last, left to right.", ["math"]),
("math-celsius-fahrenheit-formula", ["celsius ko fahrenheit mein kaise badalte hain", "fahrenheit ko celsius mein kaise badlein", "celsius fahrenheit ka formula", "formula to change celsius to fahrenheit", "temperature scale badalne ka formula", "c se f ka formula"],
 "Celsius se Fahrenheit: C x 9 / 5 + 32. Fahrenheit se Celsius: (F - 32) x 5 / 9.",
 "Celsius to Fahrenheit: C x 9 / 5 + 32. Fahrenheit to Celsius: (F - 32) x 5 / 9.", ["math"]),
("math-length-units", ["1 km mein kitne meter hote hain", "kilometre aur meter ka sambandh", "meter mein kitne centimetre hote hain", "1 meter mein kitne cm", "length ki units ka relation", "lambai ki ikaiyan kaun si hain"],
 "1 kilometre = 1000 meter, 1 meter = 100 centimetre aur 1 centimetre = 10 millimetre.",
 "1 kilometre = 1000 metres, 1 metre = 100 centimetres and 1 centimetre = 10 millimetres.", ["math"]),
("math-weight-units", ["1 kg mein kitne gram hote hain", "kilogram aur gram ka sambandh", "1 quintal mein kitne kg hote hain", "1 ton mein kitne kilo hote hain", "weight ki units ka relation", "vajan ki ikaiyan kaun si hain"],
 "1 kilogram = 1000 gram, 1 quintal = 100 kilogram aur 1 ton = 1000 kilogram.",
 "1 kilogram = 1000 grams, 1 quintal = 100 kilograms and 1 tonne = 1000 kilograms.", ["math"]),
("math-time-units", ["1 ghante mein kitne minute hote hain", "ek din mein kitne ghante hote hain", "1 minute mein kitne second hote hain", "1 saal mein kitne hafte hote hain", "samay ki ikaiyan kaun si hain", "ghanta minute second ka relation"],
 "1 minute = 60 second, 1 ghanta = 60 minute, 1 din = 24 ghante, 1 hafta = 7 din aur 1 saal = 365 din (leap year mein 366).",
 "1 minute = 60 seconds, 1 hour = 60 minutes, 1 day = 24 hours, 1 week = 7 days and 1 year = 365 days (366 in a leap year).", ["math"]),
("math-square-cube", ["square aur cube kya hote hain", "varg aur ghan kya hota hai", "what are squares and cubes", "cube number kya hota hai", "ghan kise kehte hain", "square number aur cube number mein fark"],
 "Kisi sankhya ka varg = wo sankhya x wohi sankhya, jaise 5 ka varg 25. Ghan = sankhya x sankhya x sankhya, jaise 3 ka ghan 27.",
 "The square of a number is the number times itself, like 25 for 5. The cube is the number times itself three times, like 27 for 3.", ["math"]),
("math-volume-formulas", ["cube ka volume kaise nikalte hain", "volume of a cuboid formula", "ghanabh ka ayatan kaise nikalein", "volume of a cube", "sphere aur cylinder ka volume", "ayatan ke formula kya hain"],
 "Ghan (cube) ka ayatan = bhuja ki teesri ghaat, ghanabh = lambai x chaudai x unchai, belan = pi x r x r x unchai, gola = 4/3 x pi x r ki teesri ghaat.",
 "Volume of a cube = side cubed, cuboid = length x width x height, cylinder = pi x r x r x height, sphere = 4/3 x pi x r cubed.", ["math"]),
("math-discount-formula", ["discount kaise nikalte hain", "chhoot ka formula kya hai", "how to calculate discount", "discount percentage formula", "chhoot ke baad rate kaise nikalte hain", "chhoot ke baad kimat kaise nikalein"],
 "Chhoot ki rakam = mool mulya x chhoot percent / 100. Bikri mulya = mool mulya - chhoot ki rakam.",
 "Discount amount = original price x discount percent / 100. Sale price = original price - discount amount.", ["math", "finance"]),
]
