# Science entries: (id, [question variants], hindi/hinglish answer, english answer, [tags]).  Static facts only.
E = [
("sci-water-boil", ["pani kitne degree par ubalta hai", "water boiling point", "boiling point of water", "pani ka boiling point kya hai", "at what temperature does water boil", "pani kitni garmi par ubalta hai"],
 "Saaf pani samundar tal par 100 degree Celsius (212 Fahrenheit) par ubalta hai. Pahadon par hawa ka dabaav kam hota hai, isliye wahan pani kam temperature par ubal jata hai.",
 "Pure water boils at 100 degrees Celsius (212 Fahrenheit) at sea level. On mountains the air pressure is lower, so water boils at a lower temperature.", ["science"]),
("sci-water-freeze", ["pani kitne degree par jamta hai", "water freezing point", "freezing point of water", "pani kab jam jata hai", "at what temperature does water freeze", "pani ka freezing point kya hai"],
 "Saaf pani 0 degree Celsius (32 Fahrenheit) par baraf mein badal jata hai.",
 "Pure water freezes into ice at 0 degrees Celsius (32 Fahrenheit).", ["science"]),
("sci-sky-blue", ["aasman neela kyun hota hai", "why is the sky blue", "sky blue kyun hota hai", "aasman ka rang neela kyun", "sky ka color blue kyu hai", "aakash neela kyun dikhta hai"],
 "Dhoop mein saare rang hote hain. Hawa ke kan neele rang ko sabse zyada failate hain, isliye neela rang har taraf se hamari aankhon tak aata hai.",
 "Sunlight contains all colours. Air molecules scatter blue light the most, so blue reaches our eyes from every direction of the sky.", ["science"]),
("sci-sunset-red", ["suraj dhalte waqt laal kyun dikhta hai", "why is sunset red", "sunset ka rang laal kyun hota hai", "sunrise sunset red orange kyun", "subah shaam ko aasman laal kyun hota hai", "why does the sky turn orange at sunset"],
 "Subah aur shaam ko suraj ki roshni zyada hawa se guzarti hai. Neela rang bikhar jata hai aur laal aur narangi rang bach jate hain.",
 "At sunrise and sunset sunlight travels through more air. The blue light is scattered away and the red and orange light is what remains.", ["science"]),
("sci-sun-star", ["suraj kya hai", "kya suraj ek tara hai", "is the sun a star", "suraj tara hai ya grah", "what is the sun", "suraj kitna door hai"],
 "Suraj ek tara hai, garam gas ka bahut bada gola. Wo dharti se lagbhag 15 crore km door hai aur uski roshni yahan kareeb 8 minute mein pahunchti hai.",
 "The Sun is a star, a huge ball of hot gas. It is about 150 million km from Earth and its light takes about 8 minutes to reach us.", ["science"]),
("sci-day-night", ["din aur raat kaise hote hain", "raat kyun hoti hai", "why do we have day and night", "prithvi ek chakkar kitne ghante mein lagati hai", "earth rotation ka period", "how long does earth take to rotate"],
 "Prithvi apni dhuri par lagbhag 24 ghante mein ek chakkar lagati hai. Jo hissa suraj ki taraf hota hai wahan din hota hai, baaki jagah raat.",
 "The Earth spins once on its axis in about 24 hours. The side facing the Sun has day and the other side has night.", ["science"]),
("sci-earth-orbit", ["prithvi suraj ka chakkar kitne din mein lagati hai", "earth orbit around sun how long", "ek saal mein 365 din kyun hote hain", "how long does earth take to go around the sun", "leap year kyun hota hai prithvi ka chakkar", "saal kitne din ka hota hai"],
 "Prithvi suraj ka ek chakkar lagbhag 365 din aur 6 ghante mein poora karti hai. Ye bacha hua samay jodkar har 4 saal mein ek din badhta hai (leap year).",
 "The Earth goes around the Sun once in about 365 days and 6 hours. Those extra hours add up to one extra day every 4 years, the leap year.", ["science"]),
("sci-seasons", ["mausam kyun badalte hain", "seasons kaise banti hain", "why do seasons change", "ritu parivartan kyun hota hai", "garmi sardi kyun hoti hai", "what causes the seasons"],
 "Prithvi ki dhuri lagbhag 23.5 degree jhuki hui hai. Suraj ke chakkar mein jab koi hissa suraj ki taraf jhukta hai to wahan garmi aur doosri taraf sardi hoti hai.",
 "The Earth's axis is tilted by about 23.5 degrees. As it goes around the Sun, the part tilted towards the Sun gets summer and the part tilted away gets winter.", ["science"]),
("sci-gravity", ["gravity kya hai", "gurutvakarshan kya hai", "cheezein neeche kyun girti hain", "why do things fall down", "what is gravity", "gravity kaise kaam karti hai"],
 "Gravity wo bal hai jo har cheez ko apni taraf kheenchta hai. Prithvi cheezon ko neeche kheenchti hai, isliye girne par unki raftaar har second lagbhag 9.8 meter per second badhti hai.",
 "Gravity is the force by which every mass pulls other masses towards it. Earth pulls things down, so a falling object speeds up by about 9.8 metres per second every second.", ["science"]),
("sci-moon-phases", ["chand ka aakar roz kyun badalta hai", "moon phases", "chand ki kalayein kaise banti hain", "why does the moon change shape", "purnima aur amavasya kya hai", "what is full moon and new moon"],
 "Chand khud roshni nahi deta, wo suraj ki roshni se chamakta hai. Chand dharti ka chakkar lagata hai (lagbhag 29.5 din), isliye hum uska alag alag hissa roshan dekhte hain. Poora roshan chand purnima aur bilkul dikhai na dena amavasya hai.",
 "The Moon makes no light of its own, it shines by sunlight. As it orbits the Earth (about 29.5 days) we see different parts of its sunlit half. A fully lit Moon is a full moon and an unseen one is a new moon.", ["science"]),
("sci-moon-distance", ["chand kitni door hai", "distance of moon from earth", "dharti se chand kitna door hai", "how far is the moon", "moon kitni dur hai earth se", "earth moon distance"],
 "Chand dharti se ausat lagbhag 3 lakh 84 hazaar km door hai.",
 "The Moon is on average about 384,000 km away from the Earth.", ["science"]),
("sci-eclipse", ["grahan kya hota hai", "surya grahan kyun lagta hai", "chandra grahan kaise lagta hai", "what is an eclipse", "solar eclipse kya hai", "lunar eclipse explained"],
 "Surya grahan mein chand suraj aur dharti ke beech aa jata hai aur suraj ko dhak leta hai. Chandra grahan mein dharti ki parchhai chand par padti hai. Surya grahan ko seedhe nange aankh se kabhi mat dekho.",
 "In a solar eclipse the Moon passes between the Sun and the Earth and blocks the Sun. In a lunar eclipse the Earth's shadow falls on the Moon. Never look at a solar eclipse with bare eyes.", ["science"]),
("sci-rainbow", ["indradhanush kaise banta hai", "rainbow kaise banta hai", "rainbow kyun dikhta hai", "how is a rainbow formed", "rainbow mein kitne rang hote hain", "indradhanush ke rang kaun se hain"],
 "Baarish ki boondon mein dhoop mudti hai aur alag alag rangon mein bant jati hai, isse indradhanush banta hai. Isme 7 rang hote hain: baingani, jamuni, neela, hara, peela, narangi aur laal.",
 "Sunlight bends and splits into colours inside raindrops, which makes a rainbow. It has 7 colours: violet, indigo, blue, green, yellow, orange and red.", ["science"]),
("sci-lightning", ["bijli kyun chamakti hai", "baadal kyun garajte hain", "thunder aur lightning kaise hoti hai", "what causes thunder and lightning", "thunder kya hai", "lightning kya hoti hai"],
 "Baadalon mein bijli ka charge jama hota hai aur wo ek bada cheenta bankar girta hai, wahi chamak (lightning) hai. Us se garm hui hawa ki awaaz garaj (thunder) hai. Roshni tez chalti hai isliye chamak pehle dikhti hai, aur garaj ke waqt ghar ke andar rehna chahiye.",
 "Electric charge builds up in clouds and is released as a giant spark, which is lightning. The sound of the heated air is thunder. Light travels faster so you see the flash first, and you should stay indoors during thunderstorms.", ["science"]),
("sci-photosynthesis", ["photosynthesis kya hai", "prakash sanshleshan kya hai", "paudhe khana kaise banate hain", "how do plants make food", "plants apna khana kaise banate hain", "what is photosynthesis"],
 "Paudhe patton mein hare rang ke chlorophyll se dhoop, pani aur carbon dioxide leke apna khana (glucose) banate hain. Is kaam mein oxygen nikalti hai, jisse hum saans lete hain.",
 "Plants use the green chlorophyll in their leaves to turn sunlight, water and carbon dioxide into food (glucose). They release oxygen, which we breathe.", ["science"]),
("sci-bones-count", ["insaan mein kitni haddiyan hoti hain", "how many bones in human body", "body mein kitni bones hoti hain", "adult mein kitni haddi hoti hai", "baby mein kitni haddiyan hoti hain", "number of bones in the human body"],
 "Bade insaan mein 206 haddiyan hoti hain. Bachche kareeb 300 chhoti haddiyon ke saath paida hote hain, jo badhte waqt aapas mein jud jati hain.",
 "An adult human has 206 bones. Babies are born with about 300 smaller bones that join together as they grow.", ["science", "body"]),
("sci-heart", ["dil kya kaam karta hai", "heart ka kaam kya hai", "what does the heart do", "dil kaise dhadakta hai", "heart blood kaise pump karta hai", "function of the heart"],
 "Dil ek pump hai jo poore sharir mein khoon pahunchata hai. Aaram ki halat mein bade logon ka dil aam taur par ek minute mein 60 se 100 baar dhadakta hai.",
 "The heart is a pump that sends blood around the whole body. At rest an adult heart usually beats 60 to 100 times a minute.", ["science", "body"]),
("sci-blood-groups", ["blood group kitne hote hain", "blood groups kaun kaun se hain", "how many blood groups are there", "khoon ke group kaun se hote hain", "universal donor kaun sa blood group hai", "types of blood groups"],
 "Mukhya blood group A, B, AB aur O hain, har ek positive ya negative, yani kul 8 prakar. O negative sabko red cells de sakta hai (universal donor) aur AB positive sabse le sakta hai.",
 "The main blood groups are A, B, AB and O, each positive or negative, so 8 types in all. O negative can give red cells to anyone (universal donor) and AB positive can receive from all.", ["science", "body"]),
("sci-air-gases", ["hawa mein oxygen kitni hoti hai", "hum saans mein kya lete hain", "what gases are in the air", "air mein kaun si gas kitni hoti hai", "how much oxygen is in air", "oxygen kya hai"],
 "Hawa mein lagbhag 78 percent nitrogen, 21 percent oxygen aur 1 percent baaki gas hoti hain. Hum saans mein oxygen lete hain aur carbon dioxide bahar nikalte hain.",
 "Air is about 78 percent nitrogen, 21 percent oxygen and 1 percent other gases. We breathe in oxygen and breathe out carbon dioxide.", ["science"]),
("sci-global-warming", ["global warming kya hai", "greenhouse effect kya hai", "what is the greenhouse effect", "dharti garam kyun ho rahi hai", "what is global warming", "climate change kya hota hai"],
 "Carbon dioxide aur methane jaisi greenhouse gases dharti ki garmi ko rok leti hain. Koyla aur tel jalane se ye gases badhti hain aur dharti ka ausat taapman badhta hai, ise global warming kehte hain.",
 "Greenhouse gases like carbon dioxide and methane trap heat around the Earth. Burning coal and oil adds more of them, so the average temperature rises. This is called global warming.", ["science"]),
("sci-planets", ["solar system mein kitne planets hain", "how many planets are there", "grah kitne hain", "planets ke naam batao", "names of the planets", "saur mandal mein kitne grah hain"],
 "Saur mandal mein 8 grah hain: Budh, Shukra, Prithvi, Mangal, Brihaspati, Shani, Arun aur Varun. Pluto ko 2006 se baune grah (dwarf planet) mana jata hai.",
 "There are 8 planets: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus and Neptune. Pluto has been counted as a dwarf planet since 2006.", ["science"]),
("sci-biggest-planet", ["sabse bada grah kaun sa hai", "largest planet in the solar system", "biggest planet", "sabse bada planet kaun sa hai", "jupiter kitna bada hai", "which is the biggest planet"],
 "Sabse bada grah Brihaspati (Jupiter) hai. Isme lagbhag 1300 prithviyan sama sakti hain.",
 "The biggest planet is Jupiter. More than 1,300 Earths could fit inside it.", ["science"]),
("sci-smallest-planet", ["sabse chhota grah kaun sa hai", "smallest planet in the solar system", "smallest planet", "sabse chhota planet kaun sa hai", "budh grah kitna chhota hai", "which is the smallest planet"],
 "Sabse chhota grah Budh (Mercury) hai. Wo suraj ke sabse paas hai.",
 "The smallest planet is Mercury. It is also the closest planet to the Sun.", ["science"]),
("sci-light-speed", ["light ki speed kitni hai", "prakash ki gati kitni hai", "speed of light", "roshni kitni tez chalti hai", "how fast does light travel", "prakash ki raftaar"],
 "Roshni ki raftaar lagbhag 3 lakh km (299,792 km) per second hai. Ye brahmand mein sabse tez hai.",
 "Light travels at about 300,000 km (299,792 km) per second, the fastest speed in the universe.", ["science"]),
("sci-sound", ["sound ki speed kitni hai", "awaaz kaise travel karti hai", "how does sound travel", "speed of sound in air", "space mein awaaz kyun nahi sunai deti", "why is there no sound in space"],
 "Hawa mein awaaz lagbhag 343 meter per second chalti hai. Awaaz ko chalne ke liye hawa, pani ya thos jaisa madhyam chahiye, isliye khali space mein awaaz nahi sunai deti.",
 "Sound travels at about 343 metres per second in air. It needs a medium such as air, water or a solid, so you cannot hear sound in empty space.", ["science"]),
("sci-magnet", ["magnet kaise kaam karta hai", "chumbak kya hota hai", "how does a magnet work", "magnet ke do pole kaun se hote hain", "magnetic poles kya hote hain", "what is a magnet"],
 "Har chumbak ke do pole hote hain, uttari (N) aur dakshini (S). Alag pole ek doosre ko khinchte hain aur ek jaise pole door dhakelte hain.",
 "Every magnet has two poles, north (N) and south (S). Opposite poles attract each other and like poles push apart.", ["science"]),
("sci-electricity-make", ["bijli kaise banti hai", "electricity kaise banti hai", "how is electricity generated", "bijli ghar tak kaise aati hai", "power plant kaise kaam karta hai", "bijli ghar kaise banta hai"],
 "Bijli ghar mein generator ko turbine ghumata hai. Turbine ko bhaap (koyle se), behta pani, hawa ya nuclear garmi ghumati hai. Phir taaron ke zariye bijli ghar tak aati hai.",
 "In a power station a turbine spins a generator. The turbine is driven by steam (from coal or nuclear heat), flowing water or wind. The electricity then reaches homes through wires.", ["science"]),
("sci-states-matter", ["matter ki kitni states hoti hain", "solid liquid gas kya hai", "padarth ki avasthayein kaun si hain", "states of matter", "what are solid liquid and gas", "thos taral gas kya hota hai"],
 "Padarth ki teen aam avasthayein hain: thos (solid), taral (liquid) aur gas. Bahut garam avastha mein ek chautha roop plasma bhi hota hai.",
 "Matter commonly exists in three states: solid, liquid and gas. A fourth state, plasma, exists at very high temperatures.", ["science"]),
("sci-rain-cycle", ["barish kaise hoti hai", "water cycle kya hai", "jal chakra kya hota hai", "how does rain form", "rain kaise banta hai", "baarish kyun hoti hai"],
 "Suraj ki garmi se samudra aur nadiyon ka pani bhaap banke upar jata hai. Upar thanda hone par wo badal banta hai aur boondon ke roop mein wapas girta hai, ise jal chakra kehte hain.",
 "The Sun heats sea and river water into vapour that rises. Higher up it cools into clouds and falls back as rain. This loop is called the water cycle.", ["science"]),
("sci-evaporation", ["evaporation kya hai", "vaashpikaran kya hota hai", "pani bhaap kaise banta hai", "what is evaporation", "kapde sukhte kaise hain", "how does wet cloth dry"],
 "Vaashpikaran mein pani ke kan garmi se bhaap banke hawa mein mil jate hain. Isi se geele kapde sookhte hain. Dhoop aur hawa isse tez kar dete hain.",
 "In evaporation, water turns into vapour and mixes with the air. This is how wet clothes dry. Sun and wind make it faster.", ["science"]),
("sci-sea-salt", ["samundar ka pani khara kyun hota hai", "why is sea water salty", "sea water namkeen kyun hota hai", "samudra mein namak kyun hai", "samundar ka pani peene layak kyun nahi", "why is the ocean salty"],
 "Nadiyan chattanon se ghule hue khanij samudra mein le jati hain. Pani bhaap banke ud jata hai par namak wahin reh jata hai, isliye samudra khara hota hai.",
 "Rivers carry dissolved minerals from rocks into the sea. The water evaporates but the salt stays behind, so the sea is salty.", ["science"]),
("sci-vitamin-d", ["vitamin d kahan se milta hai", "vitamin d kaise milta hai", "what is vitamin d", "vitamin d ke sources kya hain", "dhoop se vitamin d kaise banta hai", "how do we get vitamin d"],
 "Vitamin D hamari tvacha par dhoop padne se banta hai aur thoda ande, machhli aur fortified doodh se milta hai. Ye haddiyon ko majboot rakhta hai. Supplement lene se pehle doctor se poochho.",
 "Your skin makes vitamin D when sunlight falls on it, and some comes from eggs, fish and fortified milk. It keeps bones strong. Ask a doctor before taking supplements.", ["science", "health"]),
("sci-vitamin-c", ["vitamin c kis mein hota hai", "vitamin c kahan se milta hai", "which foods have vitamin c", "vitamin c ke sources", "vitamin c kya kaam karta hai", "what does vitamin c do"],
 "Vitamin C nimbu, santra, amla, amrud aur shimla mirch jaise phal aur sabziyon mein bahut hota hai. Ye chot bharne aur rog se ladne mein madad karta hai. Pakane se thoda kam ho jata hai.",
 "Vitamin C is plentiful in lemon, orange, amla, guava and bell pepper. It helps wounds heal and supports the body against illness. Cooking reduces it a little.", ["science", "health"]),
("sci-solar-energy", ["solar energy kya hai", "saur urja kya hoti hai", "solar panel kaise kaam karta hai", "how do solar panels work", "suraj se bijli kaise banti hai", "what is solar power"],
 "Solar panel mein silicon ke cell hote hain jo dhoop padne par seedhe bijli banate hain. Is bijli ko ghar mein use kiya ja sakta hai ya battery mein jama kiya ja sakta hai.",
 "Solar panels contain silicon cells that turn sunlight directly into electricity. That power can be used at home or stored in a battery.", ["science"]),
("sci-atom", ["atom kya hota hai", "parmanu kya hai", "what is an atom", "atom mein kya kya hota hai", "proton neutron electron kya hain", "parmanu ki sanrachna"],
 "Parmanu (atom) har padarth ka sabse chhota bhaag hai. Beech mein nucleus hota hai jisme proton aur neutron hote hain, aur bahar electron ghumte hain.",
 "An atom is the basic building block of matter. At the centre is a nucleus of protons and neutrons, and electrons move around it.", ["science"]),
("sci-fossil-fuel", ["fossil fuel kya hota hai", "koyla aur tel kaise bante hain", "what are fossil fuels", "non renewable energy kya hai", "kaun si urja khatam ho jati hai", "what is non renewable energy"],
 "Koyla, kaccha tel aur prakritik gas fossil fuel hain, jo lakhon saal pehle dabe hue paudhon aur jeevon se bane. Ye ek baar khatam hone par dobara nahi banti, isliye inhe non-renewable kehte hain.",
 "Coal, crude oil and natural gas are fossil fuels, formed from plants and animals buried millions of years ago. They cannot be replaced once used up, so they are called non-renewable.", ["science"]),
("sci-digestion", ["khana kaise pachta hai", "digestion kaise hota hai", "how does digestion work", "pachan tantra kya hai", "khana pet mein jakar kya hota hai", "digestive system explained"],
 "Muh mein khana chabane aur laar se tootna shuru hota hai. Phir pet aur chhoti aant mein rason se pachta hai aur poshak tatva khoon mein jate hain. Bacha hua kachra badi aant se bahar nikalta hai.",
 "Digestion starts in the mouth with chewing and saliva. Then the stomach and small intestine break food down with juices and the nutrients enter the blood. The leftover waste leaves through the large intestine.", ["science", "body"]),
("sci-teeth-count", ["insaan ke kitne daant hote hain", "how many teeth do adults have", "bachchon ke kitne daant hote hain", "doodh ke daant kitne hote hain", "number of teeth in humans", "adult mein kitne teeth hote hain"],
 "Bade insaan ke 32 daant hote hain (akal daadh milakar). Bachchon ke 20 doodh ke daant hote hain jo baad mein gir jate hain.",
 "An adult has 32 teeth, including wisdom teeth. Children have 20 baby teeth that fall out later.", ["science", "body"]),
("sci-lungs", ["phephde kya kaam karte hain", "lungs ka kaam kya hai", "what do the lungs do", "saans lene mein lungs kya karte hain", "how do we breathe", "saans lene ki prakriya kya hai"],
 "Saans lene par hawa naak se phephdon mein jati hai. Wahan oxygen khoon mein mil jati hai aur carbon dioxide bahar nikal jati hai.",
 "When you breathe in, air goes through the nose into the lungs. There oxygen enters the blood and carbon dioxide is sent out.", ["science", "body"]),
]
