#!/usr/bin/env python3
"""Generates app/src/test/java/com/nova/assistant/PersonalMemoryTest.kt from tools/memory_cases.py (same table the Python contract test uses)."""
import os, sys
HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import memory_cases as C
def k(s): return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$') + '"'
def klist(xs): return "listOf(" + ", ".join(k(x) for x in xs) + ")"
out = []
w = out.append
w('''package com.nova.assistant

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/** GENERATED by tools/gen_memory_test.py from tools/memory_cases.py (do not edit the tables here: edit memory_cases.py and regenerate). */
class PersonalMemoryTest {
    private val facts = ''' + klist(C.FACTS) + '''

    private fun parse(text: String): Logic.Cmd? = PersonalMemory.parse(Logic.norm(text))

    @Test fun parserTableMatchesParseAndClassify() {
        // (text, kind, arg)
        val rows = listOf(''')
rows = []
for t, kind, arg in C.PARSE:
    rows.append("            Triple(%s, %s, %s)" % (k(t), k(kind) if kind else "null", k(arg) if arg else "null"))
w(",\n".join(rows))
w('''        )
        for ((text, kind, arg) in rows) {
            val p = parse(text)
            val c = Logic.classify(text)
            if (kind == null) {
                assertNull("parse should ignore: $text", p)
                assertFalse("classify must not give a memory kind: $text", c != null && PersonalMemory.isMemoryKind(c.kind))
            } else {
                assertNotNull("parse: $text", p)
                assertEquals("kind of: $text", kind, p?.kind)
                if (arg != null) assertEquals("arg of: $text", arg, p?.arg)
                assertNotNull("classify: $text", c)
                assertEquals("classify kind of: $text", kind, c?.kind)
                if (arg != null) assertEquals("classify arg of: $text", arg, c?.arg)
            }
        }
    }

    @Test fun refusalTable() {
        val rows = listOf(''')
rows = []
for f, why in C.REFUSE:
    rows.append("            Pair(%s, %s)" % (k(f), k(why) if why else "null"))
w(",\n".join(rows))
w('''        )
        for ((fact, why) in rows) {
            assertEquals("refuse: $fact", why, PersonalMemory.refuseReason(Logic.norm(fact)))
            val r = PersonalMemory.add(emptyList(), fact)
            if (why == null) assertEquals("saved: $fact", "saved", r.status)
            else {
                assertEquals("refused: $fact", "refused", r.status)
                assertTrue(r.list.isEmpty())
            }
        }
    }

    @Test fun forgetTable() {
        val base = facts.subList(0, 3)
        val rows = listOf(''')
rows = []
for q, n, amb in C.FORGET:
    rows.append("            Triple(%s, %d, %s)" % (k(q), n, "true" if amb else "false"))
w(",\n".join(rows))
w('''        )
        for ((q, removed, amb) in rows) {
            val r = PersonalMemory.forget(base, q)
            assertEquals("removed for: $q", removed, r.removed)
            assertEquals("ambiguous for: $q", amb, r.ambiguous)
            assertEquals("size after: $q", base.size - removed, r.list.size)
        }
    }

    @Test fun relevantTable() {
        val rows = listOf(''')
rows = []
for q, want in C.RELEVANT:
    rows.append("            Pair(%s, %s)" % (k(q), klist(want)))
w(",\n".join(rows))
w('''        )
        for ((q, want) in rows) assertEquals("relevant for: $q", want, PersonalMemory.relevant(facts, q))
    }

    @Test fun relevantNeverMoreThanThree() {
        val many = (1..10).map { "tea fact number $it about chai" }
        assertEquals(3, PersonalMemory.relevant(many, "tell me about chai").size)
    }

    @Test fun addDedupesIgnoringCaseAndSpaces() {
        val a = PersonalMemory.add(emptyList(), "mera naam shiv hai")
        assertEquals("saved", a.status)
        val b = PersonalMemory.add(a.list, "MERA   naam shiv HAI")
        assertEquals("dup", b.status)
        assertEquals(1, b.list.size)
    }

    @Test fun addLengthLimits() {
        assertEquals("short", PersonalMemory.add(emptyList(), "ab").status)
        assertEquals("long", PersonalMemory.add(emptyList(), "x".repeat(PersonalMemory.MAX_FACT_CHARS + 1)).status)
        assertEquals("saved", PersonalMemory.add(emptyList(), "y".repeat(PersonalMemory.MAX_FACT_CHARS)).status)
    }

    @Test fun listIsLimitedAndNewestFirst() {
        var l: List<String> = emptyList()
        for (i in 0 until PersonalMemory.MAX_FACTS + 5) l = PersonalMemory.add(l, "fact about tea item$i").list
        assertEquals(PersonalMemory.MAX_FACTS, l.size)
        assertTrue(l[0].endsWith("item" + (PersonalMemory.MAX_FACTS + 4)))
        assertFalse(l.any { it.endsWith("item0") })
    }

    @Test fun controlCharactersAndTemplateMarkersAreCleaned() {
        assertEquals("a b c d", PersonalMemory.cleanFact("a\\nb\\tc<|d|>"))
    }

    @Test fun encodeDecodeRoundTrip() {
        val l = listOf("mera naam shiv hai", "meri car blue hai")
        assertEquals(l, PersonalMemory.decode(PersonalMemory.encode(l)))
        assertEquals(emptyList<String>(), PersonalMemory.decode(null))
        assertEquals(emptyList<String>(), PersonalMemory.decode(""))
    }

    @Test fun factsBlockIsEmptyWithoutFactsAndCapped() {
        assertEquals("", PersonalMemory.factsBlock(emptyList(), true))
        val b = PersonalMemory.factsBlock(listOf("one fact", "two fact", "three fact", "four fact"), true)
        assertTrue(b.contains("three fact"))
        assertFalse(b.contains("four fact"))
    }

    @Test fun repliesNeverEchoARefusedSecret() {
        val r = PersonalMemory.add(emptyList(), "my otp is 5555")
        for (en in listOf(true, false)) {
            assertFalse(PersonalMemory.saveReply(r, en).contains("5555"))
            assertFalse(PersonalMemory.saveReply(r, en).contains("otp is"))
        }
    }

    @Test fun listReplyReadsBackAndHandlesEmpty() {
        assertTrue(PersonalMemory.listReply(emptyList(), true).contains("not remembering"))
        val l = (1..12).map { "fact $it" }
        val s = PersonalMemory.listReply(l, true)
        assertTrue(s.contains("1. fact 1"))
        assertTrue(s.contains("And 4 more"))
        assertFalse(s.contains("fact 12"))
    }

    @Test fun reminderIsStillATimerNotAMemory() {
        val c = Logic.classify("yaad dilao 5 minute baad chai")
        assertFalse(c != null && PersonalMemory.isMemoryKind(c.kind))
    }
}
''')
dst = os.path.join(HERE, "..", "app", "src", "test", "java", "com", "nova", "assistant", "PersonalMemoryTest.kt")
open(dst, "w", encoding="utf8").write("\n".join(out))
print("wrote", dst)
